/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appcarnavrau;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author cleide
 */
public class Game extends javax.swing.JFrame {

    private int score;
    private File aqr = new File("arquivo.txt");

    public Game(String image) {
        initComponents();
        jLabel3.setIcon(ajustarImagem(image, jLabel3));
        score = lerArq(aqr);
    }

    public Game() {

    }

    public int lerArq(File file) {
        String linha = "";
        int valor = 0;
        try {
            try (FileReader fr = new FileReader(file)) {
                BufferedReader br = new BufferedReader(fr);
                

                while (br.ready()) {
                    linha = br.readLine();
                }
                jLabel2.setText(linha);
                br.close();
            }
        } catch (IOException ex) {
        }
        
        return valor = Integer.parseInt(linha);

    }

    public void escreverArq(File file, String valor) {
        try {
            try (FileWriter fw = new FileWriter(file)) {
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(valor);
                bw.newLine();
                bw.close();
            }
        } catch (IOException ex) {
        }

    }

    private ImageIcon ajustarImagem(String local, javax.swing.JLabel label) {
        //Cria um imagem icon a partir do local selecionado
        ImageIcon img = new ImageIcon(local);
        //Transforma o ImageIcon para Image para conseguir redimensionar     
        Image minhaImagem = img.getImage();
        //Redimenciona imagem do tamanho do Jlabel
        Image newImg = minhaImagem.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        //Cria um image icon com imagem redimencionada pro tamanho do Jlabel
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        botaoInedita1 = new javax.swing.JButton();
        botaoFeia2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoFeia1 = new javax.swing.JButton();
        botaoGata2 = new javax.swing.JButton();
        botaoGostosa1 = new javax.swing.JButton();
        botaoGordinha1 = new javax.swing.JButton();
        botaoGostosa2 = new javax.swing.JButton();
        botaoInedita2 = new javax.swing.JButton();
        botaoGata1 = new javax.swing.JButton();
        botaoGordinha2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        botaoAmiga2 = new javax.swing.JButton();
        botaoAmiga1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(435, 670));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button_voltar.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 583, 123, 46));

        botaoInedita1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button.png"))); // NOI18N
        botaoInedita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInedita1ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoInedita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 49, 46));

        botaoFeia2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button (1).png"))); // NOI18N
        botaoFeia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFeia2ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoFeia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 50, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/cooltext245650758090154.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, 40));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 115, 104));

        botaoFeia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button.png"))); // NOI18N
        botaoFeia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFeia1ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoFeia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 49, 46));

        botaoGata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button (1).png"))); // NOI18N
        botaoGata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGata2ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoGata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 50, 46));

        botaoGostosa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button.png"))); // NOI18N
        botaoGostosa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGostosa1ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoGostosa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 49, 46));

        botaoGordinha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button.png"))); // NOI18N
        botaoGordinha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGordinha1ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoGordinha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 49, 46));

        botaoGostosa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button (1).png"))); // NOI18N
        botaoGostosa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGostosa2ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoGostosa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 50, 46));

        botaoInedita2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button (1).png"))); // NOI18N
        botaoInedita2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInedita2ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoInedita2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 50, 46));

        botaoGata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button.png"))); // NOI18N
        botaoGata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGata1ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoGata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 49, 46));

        botaoGordinha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button (1).png"))); // NOI18N
        botaoGordinha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGordinha2ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoGordinha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 50, 46));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/cooltext245769439556218.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        botaoAmiga2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button (1).png"))); // NOI18N
        botaoAmiga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAmiga2ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAmiga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 50, 46));

        botaoAmiga1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/button.png"))); // NOI18N
        botaoAmiga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAmiga1ActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAmiga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 49, 46));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/cooltext245769278817273.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/cooltext245768790371077.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/gata.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 260, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/cooltext245768770788117.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/oie_transparent.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 130, 130));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcarnavrau/background.png"))); // NOI18N
        lblFundo.setText("i");
        jPanel1.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInedita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInedita1ActionPerformed
        
        score += 4;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));

    }//GEN-LAST:event_botaoInedita1ActionPerformed

    private void botaoFeia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFeia2ActionPerformed
        score -= 2;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoFeia2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_jButton12ActionPerformed

    private void botaoGordinha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGordinha2ActionPerformed
        // TODO add your handling code here:
        score -= 2;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoGordinha2ActionPerformed

    private void botaoGostosa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGostosa1ActionPerformed
        // TODO add your handling code here:
        score += 5;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoGostosa1ActionPerformed

    private void botaoGata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGata1ActionPerformed
        // TODO add your handling code here:
        score += 4;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoGata1ActionPerformed

    private void botaoAmiga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAmiga2ActionPerformed
        // TODO add your handling code here:
        score -= 1;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoAmiga2ActionPerformed

    private void botaoInedita2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInedita2ActionPerformed
        // TODO add your handling code here:
        score -= 4;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoInedita2ActionPerformed

    private void botaoFeia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFeia1ActionPerformed
        // TODO add your handling code here:
        score += 2;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoFeia1ActionPerformed

    private void botaoGordinha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGordinha1ActionPerformed
        // TODO add your handling code here:
        score += 2;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoGordinha1ActionPerformed

    private void botaoGostosa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGostosa2ActionPerformed
        // TODO add your handling code here:
        score -= 5;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoGostosa2ActionPerformed

    private void botaoGata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGata2ActionPerformed
        // TODO add your handling code here:
        score -= 4;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoGata2ActionPerformed

    private void botaoAmiga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAmiga1ActionPerformed
        // TODO add your handling code here:
        score += 1;
        jLabel2.setText(Integer.toString(score));
        escreverArq(aqr, String.valueOf(score));
    }//GEN-LAST:event_botaoAmiga1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAmiga1;
    private javax.swing.JButton botaoAmiga2;
    private javax.swing.JButton botaoFeia1;
    private javax.swing.JButton botaoFeia2;
    private javax.swing.JButton botaoGata1;
    private javax.swing.JButton botaoGata2;
    private javax.swing.JButton botaoGordinha1;
    private javax.swing.JButton botaoGordinha2;
    private javax.swing.JButton botaoGostosa1;
    private javax.swing.JButton botaoGostosa2;
    private javax.swing.JButton botaoInedita1;
    private javax.swing.JButton botaoInedita2;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables
}
